name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
        
      - name: Generate Build Files (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir build
          cmake -S ./glfw -B ./build -D BUILD_SHARED_LIBS=ON
        
      - name: Generate Build Files (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          cmake -G "Visual Studio 17 2022" -S ./glfw -B ./build -D BUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build ./build --config Release

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "Release Draft"
          draft: true
          files: |
            build/src/libglfw.so
            build/src/libglfw.dylib
            build/src/Release/glfw3.dll